// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edpshrimlntytiezfthj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkcHNocmltbG50eXRpZXpmdGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMDQxNjIsImV4cCI6MjA1ODc4MDE2Mn0.YMBUAdv8jakBDWq2mymDyWvpW6ZKvDZcFav4HKJbowM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);